from turtle import *
from random import *
def onecloud(r,g,b):
    hideturtle()
    speed(0)
    pensize(8)
    pencolor(uniform(0,0.1),uniform(0.6,1),1)
    fillcolor((r,g,b))
    begin_fill()
    seth(7)
    for i in range(randint(18,23)):
        fd(i)
        left(1)
    seth(90)
    for n in range(3):
        circle(30,200)
        right(60)
    end_fill()
hideturtle()
def clouds():
    speed(0)
    for m in range(10):
        x, y = randint(-200, 350), randint(100, 230)
        up()
        goto(x, y)
        down()
        onecloud(uniform(0,0.1),uniform(0.6,1),1)
    up()
    goto(0,0)
    down()
    seth(0)
def ground():
    hideturtle()
    speed(0)
    for i in range(400):
        pensize(randint(1,3))
        x,y=randint(-500,500),randint(-280,-80)
        r,g,b=-y/280,-y/280,-y/280
        pencolor((r,g,b))
        penup()
        goto(x,y)
        down()
        fd(randint(25,30))
def sun():
    hideturtle()
    for i in range(50):
        up()
        goto(randint(-650,-400),randint(120,340))
        down()
        pensize(9)
        pencolor(1,uniform(0.9,1),uniform(0.1,0.8))
        for n in range(randint(18,24)):
            fd(1)
            left(2)
            fd(3)
            right(2)
    up()
    goto(-600,300)
    down()
    pensize(5)
    pencolor('gold')
    fillcolor('yellow')
    begin_fill()
    for i in range(12):
        circle(30, 90)
        right(120)
    end_fill()
def onerainbow(r,g,b):
    for i in range(20):
        pencolor((r,g,b+0.03*i))
        circle(1000)
        right(0.1)
def rainbow():
    hideturtle()
    pensize(3)
    speed(0)
    up()
    goto(-750, -300)
    down()
    right(100)
    onerainbow(0.96, 0.1,0)
    onerainbow(1, 0.6, 0)
    onerainbow(1, 1, 0.1)
    onerainbow(0, 0.6, 0)
    onerainbow(0, 0.9, 0)
    onerainbow(0, 0.6, 0.4)
    onerainbow(0.7, 0.1,0.4)
def dandelion(n):
    seth(90)
    pensize(3)
    pencolor((0.1,0.1,0.2))
    fd(5)
    pensize(n)
    pencolor((0,0.3,0.4))
    fd(20)
    seth(150)
    pencolor((1,0.7,0.8))
    for i in range(9):
        fd(22)
        backward(22)
        right(15)
    up()
    seth(0)
    down()
    pensize(1)
def dandelions():
    for i in range(20):
        ls=[1,1.5,2]
        up()
        goto(randint(-600, 600), randint(-100, 200))
        down()
        dandelion(choice(ls))
        up()
        goto(0,0)
        seth(0)
        down()
def kite():
    hideturtle()
    up()
    goto(200,-300)
    seth(0)
    down()
    pensize(1)
    pencolor('black')
    fillcolor((0.1,0.1,0))
    begin_fill()
    for i in range(10):
        fd(i)
        left(1)
    seth(93)
    for i in range(14):
        fd(i)
        left(1)
    seth(180)
    for i in range(7):
        fd(i)
        right(1)
    seth(-97)
    for i in range(15):
        fd(i)
        right(1)
    end_fill()
    up()
    goto(227,-200)
    down()
    pencolor((1,0.5,0.9))
    pensize(3)
    for i in range(9):
        circle(-30,50)
        circle(30,-50)
    up()
    goto(230,-270)
    down()
    pencolor('black')
    pensize(1)
    seth(40)
    for i in range(30):
        fd(i)
        left(0.5)
    seth(-80)
    pencolor('plum')
    fillcolor('salmon')
    begin_fill()
    fd(50)
    left(120)
    fd(60)
    left(120)
    fd(50)
    end_fill()
    seth(-40)
    up()
    fd(25)
    down()
    pensize(3)
    for i in range(14):
        fd(i)
        left(1)
    up()
    goto(0,0)
    down()
    seth(0)
    pensize(1)
def grass():
    speed(0)
    for i in range(700):
        pensize(randint(3,5))
        y=randint(-400,-310)
        pencolor((uniform(0,0.2),uniform(0.9,1),uniform(0,0.5)))
        penup()
        goto(randint(-800,800),y)
        seth(0)
        pendown()
        left(90)
        circle(-50,randint(50,130))
        up()
        goto(0,0)
        seth(0)
        pensize(1)
        pencolor('white')
        down()
def oneflower(x,y):
    hideturtle()
    up()
    goto(x,y)
    down()
    speed(0)
    pensize(1)
    colors = ['yellow', 'salmon']
    fillcolor((1,0.6,0.8))
    begin_fill()
    for i in range(64):
        circle(i /8, 140)
        pencolor(colors[i % 2])
        right(90)
    end_fill()
    pencolor((0,1,0.2))
    fillcolor((0,1,0.2))
    begin_fill()
    pensize(2)
    seth(-90)
    circle(-100, 40)
    seth(135)
    circle(-60, 30)
    seth(-45)
    circle(60, 30)
    seth(45)
    circle(-60, 30)
    seth(-135)
    circle(-60, 35)
    end_fill()
    up()
    goto(0,0)
    down()
    seth(0)
def flowers():
    for i in range(10):
        oneflower(randint(-650,650),randint(-350,-270))
    up()
    goto(0,0)
    seth(0)
    pensize(1)
    pencolor('white')
    down()
def tree(length,level):
    speed(0)
    pensize(8)
    pencolor(choice(lstree))
    if level<0:
        return
    fd(length)
    left(45)
    tree(0.6*length,level-1)
    right(90)
    tree(0.6*length,level-1)
    left(45)
    backward(length)
    return
def leaves():
    speed(100)
    hideturtle()
    pensize(1)
    pencolor((0,0.8,uniform(0,0.5)))
    for i in range(230):
        up()
        goto(randint(-350,20)+randint(20,40),randint(-70,90)+randint(5,10))
        down()
        fillcolor((0,uniform(0.6,1),uniform(0,0.5)))
        begin_fill()
        circle(randint(30,50), 60)
        left(120)
        circle(randint(30,50), 60)
        end_fill()
hideturtle()
speed(0)
clouds()
sun()
rainbow()
dandelions()
ground()
kite()
grass()
flowers()
lstree=['orange','coral','salmon','black', 'green', 'violet', 'grey', 'gold', 'pink', 'darkgreen']
up()
goto(-150,-300)
down()
seth(90)
tree(200,8)
leaves()
up()
goto(520,-150)
seth(0)
down()
hideturtle()
pensize(2)
pencolor('black')
write('阳光明媚',font=('幼圆',26,'normal'))
up()
goto(520,-200)
down()
write('买庆港',font=('幼圆',14,'normal'))
done()